### PR TITLE
Add Building a VM presentation

### PR DESCRIPTION
**Pull request by ripleymj**
With my newfound Marp abilities, I was looking through old presentations to see if any were worth uploading here. This is the closest I got, and while it's a verbatim copy, I think it's also outdated by now. Is anyone in favor of merging it outdated as-is, or do I need to modernize it a bit?

### CODE REVIEW

**Comment by Advill** [comment]
I think we can get it merged now and just open an issue to update it. It's
a good starting point at least.

**Comment by kylelaker** [comment]
I have mild concerns about modernizing the format without a corresponding update to the content. It might make the content appear as fresh as the design, especially with a new file in the git history. I think it'd be fine to merge as-is without a content refresh, but I do think the update becomes a higher priority once this is merged.

**Comment by ripleymj** [comment]
Let's be honest here, I'm not thinking about this again until someone talks me into presenting it again. If it should be updated, it needs to be before merging.

**Comment by Crosse** [comment]
You should totally present this again.

*ducks*

**Comment by ripleymj** [comment]
@Advill remind me who's on the alumni lightning talks sign-up list

**Comment by ripleymj** [comment]
I think this is decently close to modernized now, and I left the git history with both the original and patch on top. Let the real trolling begin.

**Pull request merged**
