### PR TITLE
Add VM Welcome documentation

### PR DESCRIPTION
**Pull request by kylelaker**
This is the beginning of work on a welcome-to-the-VM doc to have on users' desktops when they first sign in. Since we haven't definitively identified how we're going to have users run their playbooks, this should probably not yet be merged.

Please do review and comment on the other portions of this document and feel free to push changes; otherwise I'll keep pushing revisions in response to comments that are left. I really feel that the SSH key section could use some review.

### CODE REVIEW

**Comment by ripleymj** [comment]
A few thoughts:
- Configure with provided scripts should be above the command line
- Maybe mention that playbooks are resumable
- Mention that snapshots should not be used for long-term retention
- "Attending" should be "Get involved" and mention BeInvolved and Twitter

**Comment by kylelaker** [comment]
@ripleymj Made those modifications in 4e43a2b.

**Comment by lam2mo** [comment]
Do we need to give them a hint as to where "the Menu" is?

**Comment by kylelaker** [comment]
@lam2mo We probably don't need to provide that hint. It is labeled "Menu". My concern was that later in that same section I refer to several other menus, so I added it to clarify. I am okay with it being either removed or changed.

**Comment by lam2mo** [comment]
Sounds good to me. Should I merge it?

**Comment by kylelaker** [comment]
Works for me. I've removed both the labels that were attached to this PR.

**Pull request merged**
